export const FETCHED_POSTS = 'POST/FETCHED_POSTS'
export const CREATE_POST = 'POST/CREATE_POST'
export const UPDATE_POST = 'POST/UPDATE_POST';
export const DELETE_POST = 'POST/DELETE_POST';
export const ID_ITEM_DELETE = 'POST/ID_ITEM_DELETE';
export const SHOW_MODAL_CREATE = 'POST/SHOW_MODAL_CREATE';
export const SHOW_MODAL_DELETE = 'POST/SHOW_MODAL_DELETE';