export const FETCHED_RECIPES = 'RECIPE/FETCHED_RECIPES'
export const CREATE_RECIPE = 'RECIPE/CREATE_RECIPE'
export const UPDATE_RECIPE = 'RECIPE/UPDATE_RECIPE';
export const DELETE_RECIPE = 'RECIPE/DELETE_RECIPE';
export const ID_ITEM_DELETE = 'RECIPE/ID_ITEM_DELETE';
export const STATE_MODAL_CREATE = 'RECIPE/STATE_MODAL_CREATE';
export const STATE_MODAL_DELETE = 'RECIPE/STATE_MODAL_DELETE';